ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x1 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x2 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x4 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x8 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x10 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x20 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x40 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x80 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x100 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x200 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x400 -sse

ERASE "test me\test.bsa"
bsarch pack "test me\Data\" "test me\test.bsa" -af:0x800 -sse